require-module wayland
colorscheme ayu-evo
set-option global ui_options terminal_assistant=none terminal_enable_mouse=true terminal_status_on_top=true terminal_synchronized=true terminal_info_max_width=80 terminal_padding_char=
set-option global matching_pairs ( ) { } [ ]
set-option global tabstop 4
set-option global indentwidth 4
set-option global grepcmd 'rg --column'
set-option global startup_info_version 20350518
set-option global autoinfo command
set-option global makecmd 'make -j8'
set-option global termcmd "footclientappid sh -c"

set-face global InsertCursor black,green
set-face global NormalModeCursor black,red
set-face global InfoDefault               Information
set-face global InfoBlock                 block
set-face global InfoBlockQuote            Information
set-face global InfoBullet                bullet
set-face global InfoHeader                header
set-face global InfoLink                  link
set-face global InfoLinkMono              Information
set-face global InfoMono                  mono
set-face global InfoRule                  Information
set-face global InfoDiagnosticError       Error
set-face global InfoDiagnosticWarning     Yellow
set-face global Reference +u
set-face global ReferenceBind +ub

map global normal v <a-i>
map global normal V <a-a>
map global normal <a-v> 'Z<a-i>'
map global normal <a-V> 'Z<a-i>'
map global normal l ':enter-user-mode lsp<ret>'
map global normal L ':enter-user-mode -lock lsp<ret>'
map global normal m lm
map global normal <a-m> h<a-m>
map global normal M m
map global normal t ':hop<ret>'
map global normal q ':enter-user-mode lldb<ret>'
map global normal Q ':enter-user-mode -lock lldb<ret>'
map global normal . :bn<ret>
map global normal k :bp<ret>
map global normal , '20vk'
map global normal h '20vj'
# map global normal , <c-u>
# map global normal h <c-d>
map global normal <esc> ','
map global normal <c-d> ':comment-line<ret>'
map global normal <a-esc> ':db<ret>'
map global normal <a-s-esc> ':db!<ret>'
map global normal <c-up> ':increment-sel -1<ret>'
map global normal <c-down> ':increment-sel 1<ret>'
map global normal @ 's^\s+<ret>@'
map global normal <a-@> 's^\s+<ret><a-@>'
map global normal <a-Q> Q
map global normal <a-q> q
map global normal <c-a> <c-o>
map global normal <c-r> <c-i>
map global normal <a-i> '<a-t> ;i'
map global normal <a-a> 'f ;i'
map global normal <ret> 'x_:<c-r>.<ret>'
map global normal = 'x_<a-!>%val{selections}<a-!>'
map global normal <c-/> /(?i)
map global normal <c-?> ?(?i)
map global normal <a-c-/> <a-/>(?i)
map global normal <a-c-?> <a-?>(?i)
map global normal <a-g> ':e -scratch<ret>!'

map global normal <'>  ':surround-sym<ret>'
map global normal <"> ':surround-delete<ret>'
map global user ( ':surround-nest ( )<ret>'
map global user { ':surround-nest { }<ret>'
map global user [ ':surround-nest [ ]<ret>'
map global user < ':surround-nest <lt> <gt><ret>'
map global user ) ':surround-delete<ret>)'
map global user } ':surround-delete<ret>}'
map global user ] ':surround-delete<ret>]'
map global user > ':surround-delete<ret>>'

map global user b ':b '
map global user c ':fifo '
map global user C ':e -scratch *cflow*<ret>!cflow '
map global user d ':doc '
map global user f ':f '
map global user g ':grep '
map global user F ':format<ret>'
map global user n ':new<ret>'
map global user N ':terminal kak -e "rename-session ""%val{session}_%%val{session}"""<ret>'
map global user m ':man '
map global user M ':w<ret>:make<ret>'
map global user o ':fifo -scroll'
map global user l :find-buf<ret>
map global user u ':html-open<ret>'
map global user w ':w<ret>'
map global user W ':format<ret>:w<ret>'
map global user <a-w> ':toggle-warp<ret>'
map global user <a-W> ':toggle-num-lines<ret>'
map global user q ':q<ret>'
map global user Q ':q!<ret>'
map global user x ':waq<ret>'
map global user z ':z '
map global user <ret> 'x:<c-r>.<ret>'
map global user , ':focus-toggle<ret>'
map global user <a-p> '<a-p>i<ret><esc><a-s>'

map global user y '<a-|>wl-copy<ret>'
map global user Y '<a-|>wl-copy -p<ret>'
map global user <a-y> '!wl-copy $kak_selections >/dev/null 2>&1<ret>'
map global user <a-Y> '!wl-copy -p $kak_selections >/dev/null 2>&1<ret>'
map global user p '!wl-paste -n<ret>'
map global user P '<a-!>wl-paste -n<ret>'
map global user <a-p> '!wl-paste -np<ret>'
map global user <a-P> '<a-!>wl-paste -np<ret>'

map global prompt <up> <s-tab>
map global prompt <down> <tab>
map global prompt <c-p> <down>
map global prompt <c-t> <up>
map global prompt <c-s-left> <c-B>
map global prompt <c-s-right> <c-F>
map global prompt <c-backspace> <c-w>
map global prompt <c-w> <a-f>
map global prompt <c-W> <a-F>
map global prompt <c-b> <a-b>
map global prompt <c-B> <a-B>
map global prompt <c-del> <a-d>
map global prompt <c-s-del> <a-D>
map global prompt <c-s-backspace> <c-W>
map global prompt <a-v> '%val{}<left>'
map global prompt <a-o> '%opt{}<left>'
map global prompt <a-r> '%reg{}<left>'

map global insert ( '()<left>'
map global insert { '{}<left>'
map global insert [ '[]<left>'
map global insert ) '<a-;>:close-pair )<ret>'
map global insert } '<a-;>:close-pair }<ret>'
map global insert ] '<a-;>:close-pair ]<ret>'
map global insert <'> <'><'><left>
map global insert <"> <"><"><left>

# map global insert ( <a-semicolon><a-:><a-semicolon><a-semicolon><(><a-semicolon><a-semicolon><a-semicolon>L<)><a-semicolon>H<a-semicolon>H
# map global insert { <a-semicolon><a-:><a-semicolon><a-semicolon><{><a-semicolon><a-semicolon><a-semicolon>L<}><a-semicolon>H<a-semicolon>H
# map global insert [ <a-semicolon><a-:><a-semicolon><a-semicolon><[><a-semicolon><a-semicolon><a-semicolon>L<]><a-semicolon>H<a-semicolon>H
# map global insert <'> <a-semicolon><a-:><a-semicolon><a-semicolon><'><a-semicolon><a-semicolon><a-semicolon>L<'><a-semicolon>H<a-semicolon>H
# map global insert <"> <a-semicolon><a-:><a-semicolon><a-semicolon><"><a-semicolon><a-semicolon><a-semicolon>L<"><a-semicolon>H<a-semicolon>H

map global insert <a-esc> '<a-;>:db<ret>'
map global insert <s-left> '<a-;>H'
map global insert <s-right> '<a-;>L'
map global insert <s-up> '<a-;>K'
map global insert <s-down> '<a-;>J'
map global insert <a-b> '<a-;>b'
map global insert <a-e> '<a-;>e'
map global insert <a-w> '<a-;>w'
map global insert <a-B> '<a-;>B'
map global insert <a-W> '<a-;>W'
map global insert <c-backspace> '<a-;>b<a-;><a-d>'
map global insert <c-del> '<a-;>w<a-;><a-d>'
map global insert <s-backspace> '<a-;><a-h><a-;><a-d>'
map global insert <s-del> '<a-;><a-l><a-;><a-d>'
map global insert <home> '<a-;><a-h>'
map global insert <end> '<a-;><a-l><a-;><s-right>'
map global insert <s-home> '<a-;><a-H>'
map global insert <s-end> '<a-;><a-L><a-;><s-right>'
map global insert <c-d> '<a-;>:comment-line<ret>'
map global insert <c-f> '<esc>z)Z,i'
map global insert <c-w> '<esc>z(Z,i'
map global insert <c-t> <c-n>
map global insert <a-p> <a-semicolon><a-p>
map global insert <a-P> <a-semicolon><a-P>
map global insert <s-ret> <ret><esc>O

map global goto , '<esc>:jump-anywhere<ret>'
map global goto E '<esc>:lsp-find-error<ret>'
# map global goto d '<esc>:toggle-git-diff<ret>'
map global goto n '<esc>:jump-next *grep*<ret>'
map global goto <a-n> '<esc>:jump-previous *grep*<ret>'

map global object v w
map global object V <a-w>
map global object b <esc><a-a>Bx

declare-user-mode useruser
map global user <space> ':enter-user-mode useruser<ret>'
map global useruser v ':echo %val{}<left>'
map global useruser o ':echo %opt{}<left>'
map global useruser r ':echo %reg{}<left>'
map global useruser V ':reg a %val{}<left>'
map global useruser O ':reg a %opt{}<left>'
map global useruser b ':echo %val{buffile}<ret>'
map global useruser s ':echo %sh{}<left>'
map global useruser p ':echo "%val{cursor_line}/%val{buf_line_count}"<ret>'
map global useruser e ':e %val{buffile}<a-!>'

declare-user-mode edit
map global user e ':enter-user-mode edit<ret>'
map global edit c ':edit ~/.config/kak/kakrc<ret>'
map global edit C ':edit .kak/kakrc<ret>'
map global edit d ':b *debug*<ret>'
map global edit m ':edit ~/.config/kak/marks<ret>'
map global edit n ':edit ~/devel/wip/notes/'
map global edit s ':edit -scratch<ret>'
map global edit S ':edit -scratch<ret>:set buffer filetype markdown<ret>'
map global edit h ':edit ~/.sh_history<ret>'

declare-user-mode rg
map global normal r ':enter-user-mode rg<ret>'
map global rg p ':prompt text: %{ reg r %val{text}; exec '':rg '' }<ret>'
map global rg l '<a-i>w:reg r "%reg{.} ="<ret>:rg '
map global rg r '<a-i>w:reg r "=.*?%reg{.}."<ret>:rg '
# map global rg r ':reg r " =.*?<c-r>."<ret>:rg '
map global rg . ':rg dot<ret>'
map global rg <"> ':reg r %reg{"}<ret>:rg '
map global rg , ':reg r ^[^\s].*?%reg{.}<a-!><ret>:rg '
map global rg / ':reg r %reg{/}<a-!><ret>:rg '
map global rg > ':reg r %reg{.}<ret>:rg '

map global rg G ':ctags-generate<ret>'
map global rg g ':ctags-update-tags<ret>'
map global rg b ':ctags-complete<ret>'
map global rg t ':ctags-search '
map global rg T '<a-i>w:ctags-search %reg{.}<ret>'
map global rg m '<a-i>w:ctags-funcinfo<ret>'

map global lsp l ':lsp-enable-wrapper<ret>'
map global lsp L ':lsp-disable-wrapper<ret>'
map global object a '<a-;>lsp-object<ret>' -docstring 'LSP any symbol'
map global object <a-a> '<a-;>lsp-object<ret>' -docstring 'LSP any symbol'
map global object f '<a-;>lsp-object Function Method<ret>' -docstring 'LSP function or method'
# map global object t '<a-;>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
map global object d '<a-;>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
map global object D '<a-;>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

declare-option str jump_buf '*grep*'
declare-user-mode goto-grep
map global goto-grep n ':jump-next %opt{jump_buf}<ret>'
map global goto-grep N ':jump-previous %opt{jump_buf}<ret>'

define-command -params 1 goto-grep-mode %{
    map global normal n ":jump-next %arg{1}<ret>"
    map global normal N ":jump-previous %arg{1}<ret>"

    hook -always -once global RawKey <esc> %{
        unmap global normal n
        unmap global normal N
    }
}

map global goto w '<esc>:goto-grep-mode %val{bufname}<ret>'

# declare-user-mode split
# map global normal <a-s> ':enter-user-mode split<ret>'
# map global split , 'S, <ret>'
# map global split = 'S = <ret>'
# map global split <gt> 'S <gt> <ret>'
# map global split <a-gt> 'S <gt>= <ret>'
# map global split <lt> 'S <lt> <ret>'
# map global split <a-lt> 'S <lt>= <ret>'
#

hook global BufSetOption filetype=(man|markdown|shell|make) %{ add-highlighter buffer/wrap wrap -word }
hook global BufCreate .*\.smd %{ set-option buffer filetype markdown }

# hook global ModeChange .*:.*:insert %{
#     set-face window PrimaryCursor InsertCursor
#     set-face window PrimaryCursorEol InsertCursor
# }

# hook global ModeChange .*:insert:.* %{ try %{
#     unset-face window PrimaryCursor
#     unset-face window PrimaryCursorEol
# }}

# hook global ModeChange .*:normal:next-key.* %{
#     set-face window PrimaryCursor NormalModeCursor
#     set-face window PrimaryCursorEol NormalModeCursor
# }

# hook global ModeChange .*:next-key.*:normal %{ try %{
#     unset-face window PrimaryCursor
#     unset-face window PrimaryCursorEol
# }}

# hook global BufSetOption filetype=(grep|lsp-goto) %{
# 	hook buffer -group mouse NormalKey <mouse:press:left:.*> jump
#     hook -once -always window WinSetOption filetype=.* %{ remove-hooks buffer mouse }
# }

# hook -once global KakBegin .* %{ set global jumpclient client0 }

hook global BufCreate .*\.qml %{
    set-option buffer filetype javascript
}

add-highlighter global/ show-matching -previous
autorestore-disable

# hook global KakBegin .* %{
#     evaluate-commands %sh{
#         while [ "$PWD" != "/" ]; do
#             if [ -f .kak/kakrc ]; then
#                 printf %s\\n "source '$PWD/.kak/kakrc'"
#                 break
#             fi
#             cd ..
#         done
#     }
# }
