#!/bin/sh
# export XDG_RUNTIME_DIR=/run/user/1000
# export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus

exec pipewire
# exec env XDG_RUNTIME_DIR=/run/user/1000 DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1000/bus pipewire
