[[language]]
name = "html"
language-servers = [ "vscode-html-language-server", "tailwindcss-ls"]

[[language]]
name = "css"
language-servers = [ "vscode-css-language-server", "tailwindcss-ls"]

[[language]]
name = "python"
language-servers = [ "pyright" ]

[[language]]
name = "c"
formatter = { command = "clang-format" }
# auto-format = true
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "cpp"
formatter = { command = "clang-format" }
# auto-format = true

[[language]]
name = "c-sharp"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "java"
formatter = { command = "clang-format" }
auto-format = true
indent = { tab-width = 4, unit = "    " }
roots = ["pom.xml", "build.gradle"]
# language-servers = [ "jdtls" ]

[[language]]
name = "javascript"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "json"
formatter = { command = "clang-format" }
auto-format = true

[[language]]
name = "kotlin"
auto-format = true
formatter = { command = "ktfmt", args = ["--kotlinlang-style"] }
# formatter = { command = "ktlint", args = ["-F", "--stdin"] }
# formatter = { command = "ktlint", args = ["--stdin", "--format"]}

[[language]]
name = "markdown"
formatter = { command = "mdformat"}
# auto-format = true
scope = "source.md"
file-types = ["md"]

[[language]]
name = "latex"
# config.texlab.auxDirectory = "build"
[language-server.texlab]
command = "texlab"
[language-server.texlab.config]
auxDirectory = "build"
[language-server.texlab.config.chktex]
onOpenAndSave = true
onEdit = true
[language-server.texlab.config.forwardSearch]
executable = "zathura"
args = ["--syntex-forward", "%l:%c:%f", "%p"]
# executable = "okular"
# args = ["--:nique", "file:%p#src:%l%f"]
[language-server.texlab.config.build]
forwardSearchAfter = true
onSave = true
executable = "tectonic"
args = ["-X","compile","%f","--synctex","--keep-logs","--keep-intermediates","--outdir=build","-Zshell-escape",]

[[language]]
name = "glsl"
# scope = "source.glsl"
# file-types = ["glsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]
# roots = []
# comment-token = "//"
# indent = { tab-width = 4, unit = "    " }
# injection-regex = "glsl"
# language-servers = [ "glslls"]
language-servers = [ "glsl_analyzer"]
[language-server.glsl_analyzer]
command = "glsl_analyzer"

[[language]]
name = "hlsl"
scope = "source.hlsl"
file-types = ["hlsl", "vert", "tesc", "tese", "geom", "frag", "comp" ]
language-servers = [ "ShaderTools.LanguageServer"]

# [[language]]
# name = "rust"
# language-servers = ["rust-analyzer"]
# [language_server.rust-analyzer]
# command = "rust-analyzer"
# [language_server.rust-analyzer.procMacro]
# enable = false

[[language]]
name = "test"
scope = "source.test"
file-types = ["test"]
language-servers = ["test"]
[language-server.test]
command = "simplels"
# command = "hsklls"
